# Generated by Django 3.1.4 on 2020-12-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Home', 'Home'), ('Permanent', 'Permanent')], default='Permanent', max_length=20)),
                ('street', models.CharField(max_length=250)),
                ('town', models.CharField(max_length=250)),
                ('zip_or_postal', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=14, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.URLField(null=True)),
                ('permanent_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.address')),
            ],
        ),
    ]
